### ISSUE TITLE
Sass::SyntaxError: Expected a color. Got: rgb(63,81,181)

### ISSUE THREAD

**Issue by cirdes** [rubysamurai/material_design_lite-sass#8]
Hi, 

I got this error `rake assets:clean assets:precompile --trace`. I think that is related to compass but I'm not sure.

Full stack trace

```
** Invoke assets:precompile (first_time)
** Invoke assets:environment
** Execute assets:precompile
rake aborted!
Sass::SyntaxError: Expected a color. Got: rgb(63,81,181)
  (in /Users/cirdes/Workspace/woodstock/app/assets/stylesheets/internal/custom_ml.scss:163)
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/material_design_lite-sass-1.1.3/vendor/assets/stylesheets/material/_slider.scss:163
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/material_design_lite-sass-1.1.3/vendor/assets/stylesheets/_material.scss:45
/Users/cirdes/Workspace/woodstock/app/assets/stylesheets/internal/custom_ml.scss:1
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/gradient_support.rb:166:in `assert_legal_color!'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/gradient_support.rb:153:in `initialize'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/gradient_support.rb:549:in `new'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/gradient_support.rb:549:in `block in color_stops'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/gradient_support.rb:543:in `map'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/gradient_support.rb:543:in `color_stops'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/compass-core-1.0.3/lib/compass/core/sass_extensions/functions/gradient_support.rb:592:in `radial_gradient'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/script/tree/funcall.rb:140:in `_perform'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/script/tree/node.rb:50:in `perform'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:395:in `visit_prop'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `map'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `map'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `block (2 levels) in visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `map'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:431:in `block in visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:429:in `visit_rule'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `map'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:88:in `block in with_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:88:in `with_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `block (2 levels) in visit_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `map'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:326:in `block in visit_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:88:in `block in with_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:88:in `with_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:323:in `visit_import'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `block in visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `block in with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:115:in `with_frame'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/stack.rb:79:in `with_base'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:158:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `block in visit_children'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `map'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:52:in `visit_children'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:167:in `block in visit_children'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:179:in `with_environment'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:166:in `visit_children'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `block in visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:186:in `visit_root'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/base.rb:36:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:157:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/visitors/perform.rb:8:in `visit'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/root_node.rb:36:in `css_tree'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/tree/root_node.rb:20:in `render'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sass-3.4.19/lib/sass/engine.rb:278:in `render'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/compass-rails-3.0.2/lib/compass-rails/patches/sass_importer.rb:48:in `evaluate'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/tilt-1.4.1/lib/tilt/template.rb:103:in `render'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/context.rb:197:in `block in evaluate'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `each'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/context.rb:194:in `evaluate'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:12:in `initialize'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:111:in `block in resolve_dependencies'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:105:in `each'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:105:in `resolve_dependencies'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:97:in `build_required_assets'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/processed_asset.rb:16:in `initialize'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `new'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:374:in `block in build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:395:in `circular_call_protection'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:373:in `build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/index.rb:94:in `block in build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/caching.rb:58:in `cache_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/bundled_asset.rb:37:in `init_with'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/asset.rb:24:in `from_hash'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/caching.rb:54:in `cache_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/index.rb:93:in `build_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/base.rb:287:in `find_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/index.rb:61:in `find_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:211:in `block in find_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:257:in `benchmark'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:210:in `find_asset'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:119:in `block in compile'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `each'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/sprockets/manifest.rb:118:in `compile'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:70:in `block (3 levels) in define'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-2.12.4/lib/rake/sprocketstask.rb:146:in `with_logger'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/sprockets-rails-2.3.3/lib/sprockets/rails/task.rb:69:in `block (2 levels) in define'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `call'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:240:in `block in execute'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `each'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:235:in `execute'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:179:in `block in invoke_with_call_chain'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/monitor.rb:211:in `mon_synchronize'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:172:in `invoke_with_call_chain'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/task.rb:165:in `invoke'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:150:in `invoke_task'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block (2 levels) in top_level'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `each'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:106:in `block in top_level'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:115:in `run_with_threads'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:100:in `top_level'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:78:in `block in run'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:176:in `standard_exception_handling'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rake/application.rb:75:in `run'
/Users/cirdes/Workspace/woodstock/bin/rake:8:in `<top (required)>'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
/Users/cirdes/.rvm/gems/ruby-2.2.3@sesamus/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Users/cirdes/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
-e:1:in `<main>'
```

**Comment by rubysamurai** [comment]
Hello,
Yes, this is Compass related error. Unfortunately MDL Sass syntax is not compatible with Compass and since Compass is pretty much abandoned, it is unlikely to be fixed.
